# Generated by Django 5.2.6 on 2026-01-17 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('travelers', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('ATTRACTION', 'Attraction'), ('ACCOMMODATION', 'Accommodation'), ('OTHER', 'Other')], default='ATTRACTION', max_length=20)),
                ('reservation_required', models.BooleanField(default=False)),
                ('day', models.IntegerField(default=1)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='', max_length=1000)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.trip')),
            ],
            options={
                'ordering': ['day', 'order'],
            },
        ),
    ]
