# Generated by Django 6.0.1 on 2026-01-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_expense_itinerary"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="expense",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="expense",
            name="recurrence_pattern",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="expense",
            name="split_details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="expense",
            name="split_type",
            field=models.CharField(default="equal", max_length=20),
        ),
    ]
