# Generated by Django 6.0.1 on 2026-01-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_flight"),
        ("api", "0004_suggestedevent"),
    ]

    operations = []
