# Generated by Django 6.0.1 on 2026-01-18 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_merge_0004_flight_0004_suggestedevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TravelMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("WALK", "Walk"),
                            ("BUS", "Bus"),
                            ("TRAIN", "Train"),
                            ("CYCLE", "Cycle"),
                            ("DRIVE", "Drive"),
                            ("PRIVATE_HIRE", "Private Hire"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "distance",
                    models.DecimalField(
                        decimal_places=2, help_text="Distance in km", max_digits=6
                    ),
                ),
                (
                    "duration",
                    models.DecimalField(
                        decimal_places=2, help_text="Duration in minutes", max_digits=5
                    ),
                ),
                (
                    "line_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "boarding_stop",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "alighting_stop",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "from_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_from",
                        to="api.itinerary",
                    ),
                ),
                (
                    "to_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_to",
                        to="api.itinerary",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_methods",
                        to="api.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["from_stop", "order"],
            },
        ),
    ]
