# Generated by Django 6.0.1 on 2026-01-18 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_travelmethod"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelmethod",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Estimated cost", max_digits=8
            ),
        ),
    ]
