# Generated by Django 6.0.1 on 2026-01-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_travelmethod_estimated_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelmethod",
            name="number_of_stops",
            field=models.IntegerField(
                default=0, help_text="Number of stops (for bus/train)"
            ),
        ),
    ]
