# Generated by Django 6.0.1 on 2026-01-18 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_travelmethod_number_of_stops"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelmethod",
            name="distance",
            field=models.DecimalField(
                decimal_places=2, help_text="Distance in km", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="travelmethod",
            name="duration",
            field=models.DecimalField(
                decimal_places=2, help_text="Duration in minutes", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="travelmethod",
            name="estimated_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, help_text="Estimated cost", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="travelmethod",
            name="number_of_stops",
            field=models.IntegerField(
                default=0, help_text="Number of stops for bus/train"
            ),
        ),
    ]
