# Generated by Django 5.2.6 on 2026-01-18 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_travelmethod_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=200)),
                ('activity', models.TextField()),
                ('recommended_time', models.DecimalField(decimal_places=2, help_text='Recommended time in hours', max_digits=5)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('links', models.JSONField(default=list, help_text='List of booking/info links')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_activities', to='api.trip')),
            ],
            options={
                'verbose_name_plural': 'My Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
