# Generated by Django 5.2.6 on 2026-01-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_myactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='myactivity',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='URL of the place photo', max_length=500),
        ),
    ]
