# Generated by Django 5.2.6 on 2026-01-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_myactivity_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text='List of booking/info links'),
        ),
    ]
