# Generated by Django 5.2.6 on 2026-01-18 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_itinerary_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='photo_url',
            field=models.URLField(blank=True, default='', help_text='Photo URL for the location', max_length=500),
        ),
    ]
